#pragma once

#include <ges/ges.h>
#include <gst/controller/gstinterpolationcontrolsource.h>
#include <gst/controller/gsttimedvaluecontrolsource.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace directorcut_monitor {

struct KeyPoint { GstClockTime time = 0; double value = 0.0; };
struct VisualEffectSpec { double exposure=0.0,contrast=1.0,saturation=1.0,temperature=0.0,tint=0.0,blur=0.0,sharpen=0.0,vignette=0.0; };
struct InspectorSpec { std::vector<KeyPoint>x,y,scale,rotation,opacity,speed,volume; VisualEffectSpec effects; };
struct InspectorRuntime {
    GESClip* clip=nullptr; GESTrackElement* source=nullptr; GESEffect* rotation_effect=nullptr; GESTrackElement* rotation_track=nullptr;
    GESEffect* color_effect=nullptr; GESTrackElement* color_track=nullptr; GESEffect* blur_effect=nullptr; GESTrackElement* blur_track=nullptr;
    GESTrackType type=GES_TRACK_TYPE_UNKNOWN; guint canvas_width=0,canvas_height=0; double x=0,y=0,scale=1,rotation=0,opacity=1,volume=1,speed=1;
    double exposure=0,contrast=1,saturation=1,temperature=0,tint=0,blur=0,sharpen=0,vignette=0;
};
inline double clamp(double v,double lo,double hi){return std::max(lo,std::min(hi,v));}
inline std::vector<KeyPoint> parse_points(const std::string& encoded,const std::string&(*decode)(const std::string&)){
    std::vector<KeyPoint> out;std::stringstream stream(decode(encoded));std::string pair;while(std::getline(stream,pair,',')){const auto colon=pair.find(':');if(colon==std::string::npos)continue;try{out.push_back({static_cast<GstClockTime>(std::stoull(pair.substr(0,colon))),std::stod(pair.substr(colon+1))});}catch(...){}}std::sort(out.begin(),out.end(),[](const KeyPoint&a,const KeyPoint&b){return a.time<b.time;});return out;
}
inline double value_at(const std::vector<KeyPoint>&points,GstClockTime time,double fallback){if(points.empty())return fallback;if(time<=points.front().time)return points.front().value;for(std::size_t i=0;i+1<points.size();++i){const auto&a=points[i];const auto&b=points[i+1];if(time<=b.time){const double span=static_cast<double>(std::max<GstClockTime>(1,b.time-a.time)),p=static_cast<double>(time-a.time)/span;return a.value+(b.value-a.value)*p;}}return points.back().value;}
inline bool set_child_numeric(GESTimelineElement*element,const char*property,double value){
    if(!element||!property)return false;GObject*child=nullptr;GParamSpec*pspec=nullptr;if(!ges_timeline_element_lookup_child(element,property,&child,&pspec)||!child||!pspec){if(child)g_object_unref(child);if(pspec)g_param_spec_unref(pspec);return false;}
    GValue v=G_VALUE_INIT;const GType type=G_PARAM_SPEC_VALUE_TYPE(pspec);g_value_init(&v,type);if(type==G_TYPE_DOUBLE)g_value_set_double(&v,value);else if(type==G_TYPE_FLOAT)g_value_set_float(&v,static_cast<gfloat>(value));else if(type==G_TYPE_INT)g_value_set_int(&v,static_cast<gint>(std::llround(value)));else if(type==G_TYPE_UINT)g_value_set_uint(&v,static_cast<guint>(std::max(0.0,std::round(value))));else if(type==G_TYPE_INT64)g_value_set_int64(&v,static_cast<gint64>(std::llround(value)));else if(type==G_TYPE_UINT64)g_value_set_uint64(&v,static_cast<guint64>(std::max(0.0,std::round(value))));else{g_value_unset(&v);g_object_unref(child);g_param_spec_unref(pspec);return false;}const bool ok=ges_timeline_element_set_child_property(element,property,&v);g_value_unset(&v);g_object_unref(child);g_param_spec_unref(pspec);return ok;
}
inline bool bind_points(GESTrackElement*element,const char*property,const std::vector<KeyPoint>&points,GstClockTime inpoint,double speed,double multiplier=1.0,double offset=0.0){if(!element||points.size()<2)return false;GstControlSource*source=gst_interpolation_control_source_new();if(!source)return false;g_object_set(source,"mode",GST_INTERPOLATION_MODE_LINEAR,nullptr);if(!ges_track_element_set_control_source(element,source,property,"direct-absolute")){gst_object_unref(source);return false;}auto*timed=GST_TIMED_VALUE_CONTROL_SOURCE(source);bool ok=true;for(const auto&point:points){const long double internal=static_cast<long double>(inpoint)+static_cast<long double>(point.time)*std::max(.01,speed);const auto timestamp=static_cast<GstClockTime>(std::max<long double>(0.0L,internal));ok=gst_timed_value_control_source_set(timed,timestamp,point.value*multiplier+offset)&&ok;}gst_object_unref(source);return ok;}
inline std::vector<KeyPoint> derived_geometry_points(const InspectorSpec&spec,bool x_axis,guint canvas,bool position){std::set<GstClockTime>times{0};for(const auto&p:spec.scale)times.insert(p.time);for(const auto&p:(x_axis?spec.x:spec.y))times.insert(p.time);std::vector<KeyPoint>out;for(const auto time:times){const double scale=clamp(value_at(spec.scale,time,1),.01,8),pos=value_at(x_axis?spec.x:spec.y,time,0),size=std::max(1.0,static_cast<double>(canvas)*scale);out.push_back({time,position?((static_cast<double>(canvas)-size)/2+pos):size});}return out;}
inline GESEffect* add_top_effect_if_available(GESClip*clip,const char*factory_name,const std::string&description,std::string&warning){if(!clip||!factory_name)return nullptr;GstElementFactory*factory=gst_element_factory_find(factory_name);if(!factory)return nullptr;gst_object_unref(factory);GESEffect*effect=ges_effect_new(description.c_str());if(!effect){warning=std::string("GES could not create ")+factory_name+" effect.";return nullptr;}GError*error=nullptr;if(!ges_clip_add_top_effect(clip,GES_BASE_EFFECT(effect),-1,&error)){warning=error?error->message:std::string("GES could not add ")+factory_name+" effect.";if(error)g_error_free(error);g_object_unref(effect);return nullptr;}return effect;}
inline GESEffect* ensure_rotation_effect(GESClip*clip,std::string&warning){return add_top_effect_if_available(clip,"rotate","rotate angle=0",warning);}
inline bool add_speed_effect(GESClip*clip,GESTrackType type,double speed,std::string&warning){
    speed=clamp(speed,.25,4);if(!clip||std::abs(speed-1)<1e-6)return true;std::ostringstream description;
    if(type==GES_TRACK_TYPE_VIDEO)description<<"videorate rate="<<speed;
    else if(type==GES_TRACK_TYPE_AUDIO){GstElementFactory*pitch=gst_element_factory_find("pitch");if(!pitch){warning="GStreamer pitch plugin is unavailable; native audio speed preview is disabled.";return false;}gst_object_unref(pitch);description<<"pitch tempo="<<speed;}
    else return true;
    GESEffect*effect=ges_effect_new(description.str().c_str());if(!effect){warning="GES could not create a speed effect for native preview.";return false;}GError*error=nullptr;const bool ok=ges_clip_add_top_effect(clip,GES_BASE_EFFECT(effect),-1,&error);if(!ok)warning=error?error->message:"GES could not add the speed effect.";if(error)g_error_free(error);if(!ok)g_object_unref(effect);return ok;
}
inline bool apply_video_geometry(InspectorRuntime&r){if(!r.source||!r.canvas_width||!r.canvas_height)return false;const double s=clamp(r.scale,.01,8),width=std::max(1.0,r.canvas_width*s),height=std::max(1.0,r.canvas_height*s),posx=(r.canvas_width-width)/2+r.x,posy=(r.canvas_height-height)/2+r.y;bool ok=true;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"width",width)&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"height",height)&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"posx",posx)&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"posy",posy)&&ok;return ok;}
inline double color_hue(const InspectorRuntime&r){return clamp((r.tint*.70-r.temperature*.25)/100*.28,-1,1);}
inline bool apply_color_effect(InspectorRuntime&r){if(!r.color_track)return false;bool ok=true;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.color_track),"brightness",clamp(r.exposure/8,-.5,.5))&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.color_track),"contrast",clamp(r.contrast,.25,4))&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.color_track),"saturation",clamp(r.saturation,0,4))&&ok;ok=set_child_numeric(GES_TIMELINE_ELEMENT(r.color_track),"hue",color_hue(r))&&ok;return ok;}
inline bool set_live_property(InspectorRuntime&r,const std::string&property,double value){if(!r.source)return false;if(property=="x"){r.x=value;return apply_video_geometry(r);}if(property=="y"){r.y=value;return apply_video_geometry(r);}if(property=="scale"){r.scale=clamp(value,.01,8);return apply_video_geometry(r);}if(property=="opacity"){r.opacity=clamp(value,0,1);return set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"alpha",r.opacity);}if(property=="volume"){r.volume=clamp(value,0,10);return set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"volume",r.volume);}if(property=="rotation"&&r.rotation_track){r.rotation=clamp(value,-360,360);return set_child_numeric(GES_TIMELINE_ELEMENT(r.rotation_track),"angle",r.rotation*G_PI/180);}if(property=="effect.color.exposure"){r.exposure=clamp(value,-4,4);return apply_color_effect(r);}if(property=="effect.color.contrast"){r.contrast=clamp(value,.25,4);return apply_color_effect(r);}if(property=="effect.color.saturation"){r.saturation=clamp(value,0,4);return apply_color_effect(r);}if(property=="effect.color.temperature"){r.temperature=clamp(value,-100,100);return apply_color_effect(r);}if(property=="effect.color.tint"){r.tint=clamp(value,-100,100);return apply_color_effect(r);}if(property=="effect.blur.radius"&&r.blur_track){r.blur=clamp(value,0,50);return set_child_numeric(GES_TIMELINE_ELEMENT(r.blur_track),"sigma",std::max(.1,r.blur/2));}return false;}
inline void release_runtime(InspectorRuntime&r){if(r.source){g_object_unref(r.source);r.source=nullptr;}if(r.rotation_track){g_object_unref(r.rotation_track);r.rotation_track=nullptr;}if(r.color_track){g_object_unref(r.color_track);r.color_track=nullptr;}if(r.blur_track){g_object_unref(r.blur_track);r.blur_track=nullptr;}r.rotation_effect=nullptr;r.color_effect=nullptr;r.blur_effect=nullptr;r.clip=nullptr;}
inline bool configure_inspector(GESClip*clip,GESTrackType type,const InspectorSpec&spec,guint canvas_width,guint canvas_height,GstClockTime inpoint,InspectorRuntime&r,std::string&warning){
    r.clip=clip;r.type=type;r.canvas_width=canvas_width;r.canvas_height=canvas_height;r.x=value_at(spec.x,0,0);r.y=value_at(spec.y,0,0);r.scale=clamp(value_at(spec.scale,0,1),.01,8);r.rotation=clamp(value_at(spec.rotation,0,0),-360,360);r.opacity=clamp(value_at(spec.opacity,0,1),0,1);r.volume=clamp(value_at(spec.volume,0,1),0,10);r.speed=clamp(value_at(spec.speed,0,1),.25,4);r.exposure=clamp(spec.effects.exposure,-4,4);r.contrast=clamp(spec.effects.contrast,.25,4);r.saturation=clamp(spec.effects.saturation,0,4);r.temperature=clamp(spec.effects.temperature,-100,100);r.tint=clamp(spec.effects.tint,-100,100);r.blur=clamp(spec.effects.blur,0,50);r.sharpen=clamp(spec.effects.sharpen,0,3);r.vignette=clamp(spec.effects.vignette,0,1);
    const GType source_type=type==GES_TRACK_TYPE_VIDEO?GES_TYPE_VIDEO_SOURCE:GES_TYPE_AUDIO_SOURCE;r.source=ges_clip_find_track_element(clip,nullptr,source_type);if(!r.source){warning="GES could not find the clip source track element.";return false;}add_speed_effect(clip,type,r.speed,warning);
    if(type==GES_TRACK_TYPE_VIDEO){apply_video_geometry(r);set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"alpha",r.opacity);r.color_effect=add_top_effect_if_available(clip,"videobalance","videobalance brightness=0 contrast=1 saturation=1 hue=0",warning);if(r.color_effect){r.color_track=GES_TRACK_ELEMENT(g_object_ref(r.color_effect));apply_color_effect(r);}if(r.blur>1e-6){std::ostringstream d;d<<"gaussianblur sigma="<<std::max(.1,r.blur/2);r.blur_effect=add_top_effect_if_available(clip,"gaussianblur",d.str(),warning);if(r.blur_effect)r.blur_track=GES_TRACK_ELEMENT(g_object_ref(r.blur_effect));}if(!spec.rotation.empty()||std::abs(r.rotation)>1e-6){r.rotation_effect=ensure_rotation_effect(clip,warning);if(r.rotation_effect){r.rotation_track=GES_TRACK_ELEMENT(g_object_ref(r.rotation_effect));set_child_numeric(GES_TIMELINE_ELEMENT(r.rotation_track),"angle",r.rotation*G_PI/180);}}if(canvas_width&&canvas_height){auto widths=derived_geometry_points(spec,true,canvas_width,false),heights=derived_geometry_points(spec,false,canvas_height,false),xs=derived_geometry_points(spec,true,canvas_width,true),ys=derived_geometry_points(spec,false,canvas_height,true);if(widths.size()>=2)bind_points(r.source,"width",widths,inpoint,r.speed);if(heights.size()>=2)bind_points(r.source,"height",heights,inpoint,r.speed);if(xs.size()>=2)bind_points(r.source,"posx",xs,inpoint,r.speed);if(ys.size()>=2)bind_points(r.source,"posy",ys,inpoint,r.speed);}if(spec.opacity.size()>=2)bind_points(r.source,"alpha",spec.opacity,inpoint,r.speed);if(r.rotation_track&&spec.rotation.size()>=2)bind_points(r.rotation_track,"angle",spec.rotation,inpoint,r.speed,G_PI/180);}
    else if(type==GES_TRACK_TYPE_AUDIO){set_child_numeric(GES_TIMELINE_ELEMENT(r.source),"volume",r.volume);if(spec.volume.size()>=2)bind_points(r.source,"volume",spec.volume,inpoint,r.speed);}return true;
}
} // namespace directorcut_monitor
