(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.DirectorTimeline = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const EPS = 1e-6;
  function parseFps(value,fallback=30){if(typeof value==='number'&&Number.isFinite(value)&&value>0)return value;if(typeof value==='string'){const s=value.trim();if(s.includes('/')){const[n,d]=s.split('/').map(Number);if(Number.isFinite(n)&&Number.isFinite(d)&&d!==0&&n/d>0)return n/d;}const n=Number(s);if(Number.isFinite(n)&&n>0)return n;}return fallback;}
  function frameDuration(fps){return 1/parseFps(fps)}
  function snapTime(seconds,fps){const f=parseFps(fps);return Math.max(0,Math.round((Number(seconds)||0)*f)/f)}
  function snapDelta(seconds,fps){const f=parseFps(fps);return Math.round((Number(seconds)||0)*f)/f}
  function clipEnd(clip){return(Number(clip.start)||0)+(Number(clip.duration)||0)}
  function clone(value){return JSON.parse(JSON.stringify(value))}
  function createClip(input={}){const base=clone(input||{});return{...base,id:input.id||`clip-${Math.random().toString(36).slice(2,10)}`,trackId:input.trackId||'V1',kind:input.kind||'video',name:input.name||'Clip',sourcePath:input.sourcePath||null,start:Math.max(0,Number(input.start)||0),duration:Math.max(.001,Number(input.duration)||1),sourceIn:Math.max(0,Number(input.sourceIn)||0),sourceDuration:Math.max(Number(input.sourceDuration)||Number(input.duration)||1,Number(input.duration)||1),linkedId:input.linkedId||null,keyframes:clone(input.keyframes||{}),effects:clone(input.effects||[]),audio:clone(input.audio||{}),text:clone(input.text||null),motion:clone(input.motion||null)}}
  function normalizeTimeline(timeline={}){const out=clone(timeline);out.fps=parseFps(out.fps||30);out.snapping=out.snapping!==false;out.transitions=Array.isArray(out.transitions)?out.transitions:[];out.tracks=Array.isArray(out.tracks)?out.tracks:[];out.tracks=out.tracks.map((t,i)=>({id:t.id||`${t.kind==='audio'?'A':t.kind==='caption'?'C':'V'}${i+1}`,name:t.name||t.id||`Track ${i+1}`,kind:t.kind||'video',locked:Boolean(t.locked),muted:Boolean(t.muted),hidden:Boolean(t.hidden),solo:Boolean(t.solo),height:Math.max(40,Math.min(180,Number(t.height)||52)),clips:(t.clips||[]).map(createClip).sort((a,b)=>a.start-b.start)}));return out}
  function findClip(timeline,clipId){for(const track of timeline.tracks||[]){const index=(track.clips||[]).findIndex(c=>c.id===clipId);if(index>=0)return{track,clip:track.clips[index],index}}return null}
  function findLinked(timeline,clipId){const found=findClip(timeline,clipId);if(!found?.clip?.linkedId)return null;return findClip(timeline,found.clip.linkedId)}
  function neighborSnap(timeline,clipId,rawStart,threshold=.12){const found=findClip(timeline,clipId);if(!found)return rawStart;const{clip}=found,candidates=[0];for(const track of timeline.tracks||[])for(const other of track.clips||[])if(other.id!==clipId)candidates.push(other.start,clipEnd(other));let best=rawStart,dist=threshold+EPS;for(const c of candidates){const d=Math.abs(c-rawStart);if(d<dist){best=c;dist=d}const align=c-clip.duration,de=Math.abs(align-rawStart);if(de<dist){best=align;dist=de}}return Math.max(0,best)}
  function moveClip(timelineInput,clipId,newStart,opts={}){const timeline=normalizeTimeline(timelineInput),found=findClip(timeline,clipId);if(!found||found.track.locked)return timeline;let target=Math.max(0,Number(newStart)||0);if(timeline.snapping&&opts.snap!==false)target=neighborSnap(timeline,clipId,target,opts.threshold||.12);found.clip.start=snapTime(target,timeline.fps);found.track.clips.sort((a,b)=>a.start-b.start);return timeline}
  function moveClipToTrack(timelineInput,clipId,targetTrackId,newStart,opts={}){const timeline=normalizeTimeline(timelineInput),found=findClip(timeline,clipId),target=timeline.tracks.find(t=>t.id===targetTrackId);if(!found||!target||found.track.locked||target.locked||target.kind!==found.track.kind)return timeline;let start=Math.max(0,Number(newStart)||0);if(timeline.snapping&&opts.snap!==false)start=neighborSnap(timeline,clipId,start,opts.threshold||.12);const moved={...clone(found.clip),trackId:target.id,start:snapTime(start,timeline.fps)};found.track.clips.splice(found.index,1);target.clips.push(moved);found.track.clips.sort((a,b)=>a.start-b.start);target.clips.sort((a,b)=>a.start-b.start);return timeline}
  function moveClipLinked(timelineInput,clipId,newStart,opts={}){let timeline=normalizeTimeline(timelineInput);const before=findClip(timeline,clipId);if(!before)return timeline;const delta=snapDelta(Math.max(0,Number(newStart)||0)-before.clip.start,timeline.fps),linkedId=before.clip.linkedId;timeline=moveClip(timeline,clipId,before.clip.start+delta,opts);if(linkedId){const linked=findClip(timeline,linkedId);if(linked&&!linked.track.locked)timeline=moveClip(timeline,linkedId,linked.clip.start+delta,{snap:false})}return timeline}
  function splitKeyframes(keyframes,offset,side,fps){const out={};for(const[property,frames]of Object.entries(keyframes||{})){const list=[];for(const frame of frames||[]){if(side==='left'&&frame.time<offset-EPS)list.push(clone(frame));if(side==='right'&&frame.time>=offset-EPS)list.push({...clone(frame),time:snapTime(Math.max(0,frame.time-offset),fps)})}if(list.length)out[property]=list}return out}
  function rippleDelete(timelineInput,start,end,trackIds=null){const timeline=normalizeTimeline(timelineInput),a=snapTime(Math.min(start,end),timeline.fps),b=snapTime(Math.max(start,end),timeline.fps),cut=Math.max(0,b-a);if(cut<=EPS)return timeline;const allow=trackIds?new Set(trackIds):null;for(const track of timeline.tracks){if(track.locked||(allow&&!allow.has(track.id)))continue;const next=[];for(const clip of track.clips){const ce=clipEnd(clip);if(ce<=a+EPS){next.push(clip);continue}if(clip.start>=b-EPS){clip.start=snapTime(Math.max(0,clip.start-cut),timeline.fps);next.push(clip);continue}if(clip.start<a&&ce>b){const offsetA=snapTime(a-clip.start,timeline.fps),offsetB=snapTime(b-clip.start,timeline.fps),rightId=`${clip.id}-rd-${Math.round(b*timeline.fps)}-${Math.random().toString(36).slice(2,6)}`,left={...clone(clip),duration:offsetA,keyframes:splitKeyframes(clip.keyframes,offsetA,'left',timeline.fps)},right={...clone(clip),id:rightId,start:a,duration:snapTime(ce-b,timeline.fps),sourceIn:snapTime(clip.sourceIn+offsetB,timeline.fps),keyframes:splitKeyframes(clip.keyframes,offsetB,'right',timeline.fps)};if(left.duration>=frameDuration(timeline.fps))next.push(left);if(right.duration>=frameDuration(timeline.fps))next.push(right);continue}if(clip.start<a&&ce>a){const offset=snapTime(a-clip.start,timeline.fps);clip.duration=offset;clip.keyframes=splitKeyframes(clip.keyframes,offset,'left',timeline.fps);if(clip.duration>=frameDuration(timeline.fps))next.push(clip);continue}if(clip.start<b&&ce>b){const trim=snapTime(b-clip.start,timeline.fps);clip.sourceIn=snapTime(clip.sourceIn+trim,timeline.fps);clip.duration=snapTime(ce-b,timeline.fps);clip.start=a;clip.keyframes=splitKeyframes(clip.keyframes,trim,'right',timeline.fps);if(clip.duration>=frameDuration(timeline.fps))next.push(clip);continue}}
      track.clips=next.sort((x,y)=>x.start-y.start)}return timeline}
  function splitAt(timelineInput,time,trackIds=null){const timeline=normalizeTimeline(timelineInput),t=snapTime(time,timeline.fps),frame=frameDuration(timeline.fps),allow=trackIds?new Set(trackIds):null;const splitMap=new Map();for(const track of timeline.tracks){if(track.locked||(allow&&!allow.has(track.id)))continue;const result=[];for(const clip of track.clips){const end=clipEnd(clip);if(t<=clip.start+frame*.5||t>=end-frame*.5){result.push(clip);continue}const offset=snapTime(t-clip.start,timeline.fps),rightId=`${clip.id}-r-${Math.round(t*timeline.fps)}-${Math.random().toString(36).slice(2,6)}`,left={...clone(clip),duration:offset,keyframes:splitKeyframes(clip.keyframes,offset,'left',timeline.fps)},right={...clone(clip),id:rightId,start:t,duration:snapTime(end-t,timeline.fps),sourceIn:snapTime(clip.sourceIn+offset,timeline.fps),keyframes:splitKeyframes(clip.keyframes,offset,'right',timeline.fps)};splitMap.set(clip.id,rightId);result.push(left,right)}track.clips=result.sort((a,b)=>a.start-b.start)}for(const track of timeline.tracks)for(const clip of track.clips){if(splitMap.has(clip.linkedId)&&clip.start>=t-EPS)clip.linkedId=splitMap.get(clip.linkedId);else if(splitMap.has(clip.id)){const originalLinked=clip.linkedId;if(originalLinked&&splitMap.has(originalLinked)){const rightId=splitMap.get(clip.id),right=findClip(timeline,rightId);if(right)right.clip.linkedId=splitMap.get(originalLinked)}}}return timeline}
  function rollBoundary(timelineInput,leftId,rightId,deltaSeconds){const timeline=normalizeTimeline(timelineInput),leftFound=findClip(timeline,leftId),rightFound=findClip(timeline,rightId);if(!leftFound||!rightFound||leftFound.track.id!==rightFound.track.id||leftFound.track.locked)return timeline;const left=leftFound.clip,right=rightFound.clip,frame=frameDuration(timeline.fps),delta=snapDelta(deltaSeconds,timeline.fps),maxLeftGrow=Math.max(0,left.sourceDuration-(left.sourceIn+left.duration)),maxRightTrim=Math.max(0,right.duration-frame),maxLeftTrim=Math.max(0,left.duration-frame),maxRightGrow=Math.max(0,right.sourceIn),clamped=Math.max(-Math.min(maxLeftTrim,maxRightGrow),Math.min(delta,maxLeftGrow,maxRightTrim));if(Math.abs(clamped)<=EPS)return timeline;left.duration=snapTime(left.duration+clamped,timeline.fps);right.start=snapTime(right.start+clamped,timeline.fps);right.sourceIn=snapTime(right.sourceIn+clamped,timeline.fps);right.duration=snapTime(right.duration-clamped,timeline.fps);return timeline}
  function slipClip(timelineInput,clipId,deltaSeconds){const timeline=normalizeTimeline(timelineInput),found=findClip(timeline,clipId);if(!found||found.track.locked)return timeline;const clip=found.clip,maxIn=Math.max(0,clip.sourceDuration-clip.duration);clip.sourceIn=snapTime(Math.max(0,Math.min(maxIn,clip.sourceIn+snapDelta(deltaSeconds,timeline.fps))),timeline.fps);return timeline}
  function slipClipLinked(timelineInput,clipId,deltaSeconds){let timeline=normalizeTimeline(timelineInput);const found=findClip(timeline,clipId);if(!found)return timeline;const linkedId=found.clip.linkedId;timeline=slipClip(timeline,clipId,deltaSeconds);if(linkedId)timeline=slipClip(timeline,linkedId,deltaSeconds);return timeline}
  function slideClip(timelineInput,clipId,deltaSeconds){const timeline=normalizeTimeline(timelineInput),found=findClip(timeline,clipId);if(!found||found.track.locked)return timeline;const track=found.track,i=found.index,prev=track.clips[i-1],next=track.clips[i+1];if(!prev||!next)return moveClip(timeline,clipId,found.clip.start+deltaSeconds);const frame=frameDuration(timeline.fps),delta=snapDelta(deltaSeconds,timeline.fps),prevTrim=Math.max(0,prev.duration-frame),nextHeadroom=Math.max(0,next.sourceIn),prevTailroom=Math.max(0,prev.sourceDuration-(prev.sourceIn+prev.duration)),nextTrim=Math.max(0,next.duration-frame),minDelta=-Math.min(prevTrim,nextHeadroom),maxDelta=Math.min(prevTailroom,nextTrim),d=Math.max(minDelta,Math.min(maxDelta,delta));if(Math.abs(d)<=EPS)return timeline;prev.duration=snapTime(prev.duration+d,timeline.fps);found.clip.start=snapTime(found.clip.start+d,timeline.fps);next.start=snapTime(next.start+d,timeline.fps);next.sourceIn=snapTime(next.sourceIn+d,timeline.fps);next.duration=snapTime(next.duration-d,timeline.fps);return timeline}
  function addKeyframe(timelineInput,clipId,property,time,value){const timeline=normalizeTimeline(timelineInput),found=findClip(timeline,clipId);if(!found||found.track.locked)return timeline;const local=snapTime(Math.max(0,Math.min(found.clip.duration,time-found.clip.start)),timeline.fps),list=Array.isArray(found.clip.keyframes[property])?found.clip.keyframes[property]:[],filtered=list.filter(k=>Math.abs(k.time-local)>frameDuration(timeline.fps)/2);filtered.push({time:local,value:Number(value)});filtered.sort((a,b)=>a.time-b.time);found.clip.keyframes[property]=filtered;return timeline}
  function duration(timelineInput){const timeline=normalizeTimeline(timelineInput);let max=0;for(const track of timeline.tracks)for(const clip of track.clips)max=Math.max(max,clipEnd(clip));return max}
  return{parseFps,frameDuration,snapTime,snapDelta,clipEnd,createClip,normalizeTimeline,findClip,findLinked,moveClip,moveClipToTrack,moveClipLinked,rippleDelete,splitAt,rollBoundary,slipClip,slipClipLinked,slideClip,addKeyframe,duration};
});