const { app, BrowserWindow, dialog, ipcMain } = require('electron');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { pathToFileURL } = require('url');
const ROOT = path.resolve(__dirname, '..');
const UI = path.join(ROOT, 'prototype', 'index.html');
const { runProcess, probeMedia, renderCuts, wordsToSrt, prepareMediaArtifacts } = require('./media-utils');
const { detectOllama, warmModel, chatOllama } = require('./ollama-client');
const { detectGStreamer } = require('./gstreamer');
function createWindow(){const win=new BrowserWindow({width:1640,height:1000,minWidth:1120,minHeight:740,backgroundColor:'#090a0d',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});win.loadFile(UI);}
function skillContext(){const skillDir=path.join(ROOT,'skills');if(!fs.existsSync(skillDir))return'';return fs.readdirSync(skillDir).filter(f=>f.endsWith('.md')).sort().map(f=>`# ${f}\n${fs.readFileSync(path.join(skillDir,f),'utf8')}`).join('\n\n');}
function autosavePath(){return path.join(app.getPath('userData'),'autosave.directorcut');}
function safeAttachment(filePath){const stat=fs.statSync(filePath),ext=path.extname(filePath).toLowerCase(),textLike=['.txt','.md','.json','.csv','.srt','.vtt','.html','.css','.js','.ts','.py','.cpp','.h','.hpp'].includes(ext),imageLike=['.png','.jpg','.jpeg','.webp','.gif','.bmp','.svg'].includes(ext),videoLike=['.mp4','.mov','.mkv','.webm','.m4v','.avi'].includes(ext),audioLike=['.mp3','.wav','.m4a','.aac','.flac','.ogg'].includes(ext);let text=null;if(textLike&&stat.size<=2*1024*1024){try{text=fs.readFileSync(filePath,'utf8');}catch(_){}}return{name:path.basename(filePath),path:filePath,url:pathToFileURL(filePath).toString(),size:stat.size,kind:imageLike?'image':videoLike?'video':audioLike?'audio':textLike?'document':'file',text};}
function sanitizeOperations(operations,payload){if(!Array.isArray(operations))return[];const duration=Math.max(0,Number(payload?.project?.duration||0)),allowed=new Set(['seek','split_at','remove_range','add_marker','move_clip','add_keyframe']),clampTime=value=>{const n=Math.max(0,Number(value)||0);return duration>0?Math.min(duration,n):n;};return operations.slice(0,24).flatMap(op=>{if(!op||!allowed.has(op.type))return[];if(op.type==='seek'||op.type==='split_at'||op.type==='add_marker')return[{type:op.type,time:clampTime(op.time)}];if(op.type==='remove_range'){const start=clampTime(op.start),end=clampTime(op.end);if(Math.abs(end-start)<.02)return[];return[{type:op.type,start:Math.min(start,end),end:Math.max(start,end)}];}if(op.type==='move_clip'){if(!op.clipId)return[];return[{type:op.type,clipId:String(op.clipId),newStart:clampTime(op.newStart)}];}if(op.type==='add_keyframe'){if(!op.clipId||!op.property||!Number.isFinite(Number(op.value)))return[];return[{type:op.type,clipId:String(op.clipId),property:String(op.property),time:clampTime(op.time),value:Number(op.value)}];}return[];});}
ipcMain.handle('media:pick',async()=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'Video',extensions:['mp4','mov','mkv','webm','m4v','avi']}]});if(r.canceled||!r.filePaths[0])return null;return probeMedia(r.filePaths[0]);});
ipcMain.handle('attachment:pick',async()=>{const r=await dialog.showOpenDialog({properties:['openFile','multiSelections']});if(r.canceled)return[];return r.filePaths.slice(0,12).map(safeAttachment);});
ipcMain.handle('script:pick',async()=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'Script',extensions:['txt','md']}]});if(r.canceled||!r.filePaths[0])return null;return{path:r.filePaths[0],name:path.basename(r.filePaths[0]),text:fs.readFileSync(r.filePaths[0],'utf8')};});
ipcMain.handle('project:open',async()=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'DirectorCut Project',extensions:['directorcut','json']}]});if(r.canceled||!r.filePaths[0])return null;return JSON.parse(fs.readFileSync(r.filePaths[0],'utf8'));});
ipcMain.handle('project:save',async(_e,project)=>{const defaultName=`${(project.name||'untitled').replace(/[^a-z0-9-_]+/gi,'-')}.directorcut`,r=await dialog.showSaveDialog({defaultPath:defaultName,filters:[{name:'DirectorCut Project',extensions:['directorcut']}]});if(r.canceled||!r.filePath)return null;fs.writeFileSync(r.filePath,JSON.stringify(project,null,2),'utf8');return{path:r.filePath};});
ipcMain.handle('project:autosave',async(_e,project)=>{const target=autosavePath(),temp=`${target}.tmp`;fs.writeFileSync(temp,JSON.stringify({...project,autosavedAt:new Date().toISOString()},null,2),'utf8');fs.renameSync(temp,target);return{path:target};});
ipcMain.handle('project:autosave-read',async()=>{const target=autosavePath();if(!fs.existsSync(target))return null;try{return JSON.parse(fs.readFileSync(target,'utf8'));}catch(_){return null;}});
ipcMain.handle('project:autosave-clear',async()=>{try{fs.rmSync(autosavePath(),{force:true});}catch(_){}return true;});
ipcMain.handle('video:export',async(_e,project)=>{const r=await dialog.showSaveDialog({defaultPath:`${project.name||'directorcut-export'}.mp4`,filters:[{name:'MP4 Video',extensions:['mp4']}]});if(r.canceled||!r.filePath)return null;return renderCuts({sourcePath:project.media?.path,duration:Number(project.media?.duration||0),removeRanges:project.removeRanges||[],outputPath:r.filePath,frameRate:project.media?.frameRate||project.timeline?.fps||30});});
ipcMain.handle('media:prepare',async(_e,{media,proxy=false})=>{if(!media?.path)throw new Error('Load media first.');const cacheRoot=path.join(app.getPath('userData'),'media-cache');return prepareMediaArtifacts({sourcePath:media.path,duration:Number(media.duration||0),hasAudio:media.hasAudio!==false,cacheRoot,generateProxyFile:Boolean(proxy)});});
ipcMain.handle('subtitle:export',async(_e,project)=>{if(!project.transcript?.words?.length)throw new Error('No word-timestamp transcript is loaded.');const r=await dialog.showSaveDialog({defaultPath:`${project.name||'captions'}.srt`,filters:[{name:'SubRip Captions',extensions:['srt']}]});if(r.canceled||!r.filePath)return null;fs.writeFileSync(r.filePath,wordsToSrt(project.transcript.words),'utf8');return{path:r.filePath};});
ipcMain.handle('transcribe:run',async(_e,{mediaPath,model})=>{if(!mediaPath)throw new Error('Load a video first.');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'directorcut-transcript-')),out=path.join(temp,'transcript.json'),py=process.platform==='win32'?'python':'python3';try{await runProcess(py,[path.join(ROOT,'scripts','transcribe_local.py'),mediaPath,'--model',model||'small','-o',out]);return JSON.parse(fs.readFileSync(out,'utf8'));}finally{fs.rmSync(temp,{recursive:true,force:true});}});
ipcMain.handle('ai:status',async()=>{const[ollama,gstreamer]=await Promise.all([detectOllama(),detectGStreamer()]);return{ollama,gstreamer};});
ipcMain.handle('ai:warm',async(_e,model)=>{try{return await warmModel(model);}catch(error){return{ok:false,error:String(error.message||error)};}});
ipcMain.handle('director:ask',async(_e,payload)=>{const workspaceMode=payload.workspaceMode==='Director'?'Director':'Manual',directorPolicy=['Ask','Co-edit','Auto'].includes(payload.directorPolicy)?payload.directorPolicy:'Co-edit',system=`You are DirectorCut, a professional video editor and natural conversational assistant running locally on the user's computer.\n\nThe workspace has two modes:\n- Manual: chat, explain, search, analyze, and advise. NEVER create editing operations.\n- Director: editing tasks may return typed operations. Ask means never mutate; Co-edit proposes operations; Auto may perform validated operations.\n\nClassify the user's message as conversation, analysis, search, or edit_task. A normal conversation must stay a conversation even when a video project is open. Only return edit operations when the user clearly requests an editing action and workspaceMode is Director. Prefer the smallest reversible edit. Never claim an operation happened until the host applies it. Use the provided current time, selection, transcript and timeline IDs instead of inventing context. Keep ordinary conversation natural and concise.\n\nInstalled skills:\n${skillContext()}`;const status=await detectOllama();if(status.running&&payload.model){try{const result=await chatOllama({model:payload.model,system,messages:payload.history||[],payload:{...payload,workspaceMode,directorPolicy}});let operations=sanitizeOperations(result.operations,payload);if(workspaceMode!=='Director'||directorPolicy==='Ask'||result.intent!=='edit_task')operations=[];return{available:true,...result,operations,workspaceMode,directorPolicy};}catch(error){return{available:false,provider:'ollama',error:String(error.message||error)};}}const endpoint=process.env.DIRECTORCUT_LLM_URL||'http://127.0.0.1:8080/v1/chat/completions',body={model:process.env.DIRECTORCUT_LLM_MODEL||'local-model',temperature:.35,messages:[{role:'system',content:system},...(payload.history||[]).slice(-10),{role:'user',content:JSON.stringify(payload)}]};try{const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)});if(!res.ok)throw new Error(`Local model HTTP ${res.status}`);const json=await res.json();return{available:true,provider:'llama.cpp',model:body.model,intent:'conversation',text:json.choices?.[0]?.message?.content||'No response from local Director model.',operations:[]};}catch(error){return{available:false,error:String(error.message||error)};}});
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
