const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { pathToFileURL } = require('url');
function runProcess(command,args,opts={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,...opts});let stdout='',stderr='';child.stdout?.on('data',d=>stdout+=d.toString());child.stderr?.on('data',d=>stderr+=d.toString());child.on('error',reject);child.on('close',code=>code===0?resolve({stdout,stderr}):reject(new Error(stderr||`${command} exited ${code}`)));});}
async function probeMedia(mediaPath){const{stdout}=await runProcess('ffprobe',['-v','error','-show_entries','format=duration:stream=index,codec_type,codec_name,width,height,r_frame_rate,avg_frame_rate,sample_rate,channels','-of','json',mediaPath]);const data=JSON.parse(stdout),video=(data.streams||[]).find(s=>s.codec_type==='video')||{},audio=(data.streams||[]).find(s=>s.codec_type==='audio')||{};return{path:mediaPath,name:path.basename(mediaPath),url:pathToFileURL(mediaPath).toString(),duration:Number(data.format?.duration||0),width:video.width||0,height:video.height||0,videoCodec:video.codec_name||null,audioCodec:audio.codec_name||null,frameRate:video.avg_frame_rate||video.r_frame_rate||null,sampleRate:audio.sample_rate?Number(audio.sample_rate):null,channels:audio.channels||null,hasAudio:Boolean(audio.codec_name)};}
function parseFps(value,fallback=30){if(typeof value==='number'&&Number.isFinite(value)&&value>0)return value;if(typeof value==='string'){if(value.includes('/')){const[a,b]=value.split('/').map(Number);if(a>0&&b>0)return a/b;}const n=Number(value);if(n>0)return n;}return fallback;}
function snapSeconds(seconds,fps){const f=parseFps(fps);return Math.max(0,Math.round((Number(seconds)||0)*f)/f);}
function normalizeRanges(ranges,duration,fps=30){const clean=(ranges||[]).map(r=>({start:snapSeconds(Math.max(0,Number(r.start)||0),fps),end:snapSeconds(Math.min(duration,Number(r.end)||0),fps)})).filter(r=>r.end-r.start>=1/parseFps(fps)).sort((a,b)=>a.start-b.start),merged=[];for(const r of clean){const prev=merged[merged.length-1];if(prev&&r.start<=prev.end+.5/parseFps(fps))prev.end=Math.max(prev.end,r.end);else merged.push({...r});}return merged;}
function keepRanges(removeRanges,duration,fps=30){const removed=normalizeRanges(removeRanges,duration,fps),keep=[];let cursor=0;for(const r of removed){if(r.start>cursor)keep.push({start:cursor,end:r.start});cursor=Math.max(cursor,r.end);}if(cursor<duration)keep.push({start:cursor,end:duration});return keep.filter(r=>r.end-r.start>=1/parseFps(fps));}
async function renderCuts({sourcePath,duration,removeRanges,outputPath,frameRate=30}){if(!sourcePath)throw new Error('No source video is loaded.');const fps=parseFps(frameRate),keep=keepRanges(removeRanges,duration,fps);if(!keep.length)throw new Error('The edit removes the entire video.');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'directorcut-'));try{const segments=[];for(let i=0;i<keep.length;i++){const r=keep[i],seg=path.join(temp,`segment-${String(i).padStart(4,'0')}.mp4`);await runProcess('ffmpeg',['-y','-i',sourcePath,'-ss',r.start.toFixed(6),'-t',(r.end-r.start).toFixed(6),'-map','0:v:0?','-map','0:a:0?','-c:v','libx264','-preset','veryfast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',seg]);segments.push(seg);}if(segments.length===1)fs.copyFileSync(segments[0],outputPath);else{const list=path.join(temp,'concat.txt');fs.writeFileSync(list,segments.map(s=>`file '${s.replace(/'/g,"'\\''")}'`).join('\n'));await runProcess('ffmpeg',['-y','-f','concat','-safe','0','-i',list,'-c','copy','-movflags','+faststart',outputPath]);}return{outputPath,keptSegments:keep.length,removedRanges:normalizeRanges(removeRanges,duration,fps).length,frameRate:fps};}finally{fs.rmSync(temp,{recursive:true,force:true});}}
function cacheKey(sourcePath){const stat=fs.statSync(sourcePath);return crypto.createHash('sha1').update(`${sourcePath}|${stat.size}|${stat.mtimeMs}`).digest('hex').slice(0,16);}
async function generateWaveform(sourcePath,outputPath){await runProcess('ffmpeg',['-y','-i',sourcePath,'-map','0:a:0?','-filter_complex','aformat=channel_layouts=mono,showwavespic=s=1800x180:split_channels=0','-frames:v','1',outputPath]);return outputPath;}
async function generateThumbnails(sourcePath,outputDir,duration,count=18){fs.mkdirSync(outputDir,{recursive:true});const safeDuration=Math.max(1,Number(duration)||1),interval=Math.max(.5,safeDuration/Math.max(1,count)),pattern=path.join(outputDir,'thumb-%03d.jpg');await runProcess('ffmpeg',['-y','-i',sourcePath,'-vf',`fps=1/${interval.toFixed(4)},scale=240:-2`,'-frames:v',String(count),'-q:v','4',pattern]);return fs.readdirSync(outputDir).filter(f=>/^thumb-\d+\.jpg$/i.test(f)).sort().map(f=>path.join(outputDir,f));}
async function generateProxy(sourcePath,outputPath){await runProcess('ffmpeg',['-y','-i',sourcePath,'-map','0:v:0?','-map','0:a:0?', '-vf',"scale='min(1280,iw)':-2",'-c:v','libx264','-preset','ultrafast','-crf','25','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart',outputPath]);return outputPath;}
async function prepareMediaArtifacts({sourcePath,duration,hasAudio=true,cacheRoot,generateProxyFile=false}){if(!sourcePath)throw new Error('No source media path.');const root=path.join(cacheRoot,cacheKey(sourcePath)),thumbDir=path.join(root,'thumbs'),waveformPath=path.join(root,'waveform.png'),proxyPath=path.join(root,'proxy.mp4');fs.mkdirSync(root,{recursive:true});let waveform=null;if(hasAudio){try{if(!fs.existsSync(waveformPath))await generateWaveform(sourcePath,waveformPath);waveform=pathToFileURL(waveformPath).toString();}catch(_){waveform=null;}}let thumbnails=[];try{const existing=fs.existsSync(thumbDir)?fs.readdirSync(thumbDir).filter(f=>/^thumb-\d+\.jpg$/i.test(f)):[];const files=existing.length?existing.sort().map(f=>path.join(thumbDir,f)):await generateThumbnails(sourcePath,thumbDir,duration);thumbnails=files.map(f=>pathToFileURL(f).toString());}catch(_){thumbnails=[];}let proxy=null;if(generateProxyFile){try{if(!fs.existsSync(proxyPath))await generateProxy(sourcePath,proxyPath);proxy=pathToFileURL(proxyPath).toString();}catch(_){proxy=null;}}return{cacheDir:root,waveform,thumbnails,proxy};}
function msToSrt(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),z=Math.floor(ms%1000);return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(z).padStart(3,'0')}`;}
function wordsToSrt(words){const groups=[];let current=[];for(const w of words||[]){current.push(w);const punctuation=/[.!?]$/.test(w.text||''),span=current.length?current[current.length-1].end_ms-current[0].start_ms:0;if(current.length>=7||punctuation||span>=3200){groups.push(current);current=[];}}if(current.length)groups.push(current);return groups.map((g,i)=>`${i+1}\n${msToSrt(g[0].start_ms)} --> ${msToSrt(g[g.length-1].end_ms)}\n${g.map(w=>w.text).join(' ')}\n`).join('\n');}
module.exports={runProcess,probeMedia,parseFps,snapSeconds,normalizeRanges,keepRanges,renderCuts,generateWaveform,generateThumbnails,generateProxy,prepareMediaArtifacts,msToSrt,wordsToSrt};
