const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('directorcut', {
  desktop: true,
  pickMedia: () => ipcRenderer.invoke('media:pick'),
  pickManyMedia: () => ipcRenderer.invoke('media:pick-many'),
  pickAttachments: () => ipcRenderer.invoke('attachment:pick'),
  pickScript: () => ipcRenderer.invoke('script:pick'),
  openProject: () => ipcRenderer.invoke('project:open'),
  saveProject: project => ipcRenderer.invoke('project:save', project),
  autosaveProject: project => ipcRenderer.invoke('project:autosave', project),
  readAutosave: () => ipcRenderer.invoke('project:autosave-read'),
  clearAutosave: () => ipcRenderer.invoke('project:autosave-clear'),
  exportVideo: project => ipcRenderer.invoke('video:export', project),
  exportSrt: project => ipcRenderer.invoke('subtitle:export', project),
  prepareMedia: (media, proxy = false) => ipcRenderer.invoke('media:prepare', { media, proxy }),
  transcribe: (mediaPath, model = 'small') => ipcRenderer.invoke('transcribe:run', { mediaPath, model }),
  localAIStatus: () => ipcRenderer.invoke('ai:status'),
  warmModel: model => ipcRenderer.invoke('ai:warm', model),
  askDirector: payload => ipcRenderer.invoke('director:ask', payload),

  programMonitorStatus: () => ipcRenderer.invoke('monitor:status'),
  programMonitorBounds: rect => ipcRenderer.invoke('monitor:bounds', rect),
  programMonitorLoad: (project, position = 0) => ipcRenderer.invoke('monitor:load', { project, position }),
  programMonitorPlay: () => ipcRenderer.invoke('monitor:play'),
  programMonitorPause: () => ipcRenderer.invoke('monitor:pause'),
  programMonitorSeek: seconds => ipcRenderer.invoke('monitor:seek', seconds),
  programMonitorPosition: () => ipcRenderer.invoke('monitor:position'),
  programMonitorVisible: visible => ipcRenderer.invoke('monitor:visible', visible),
  programMonitorStop: () => ipcRenderer.invoke('monitor:stop')
});
